### ISSUE TITLE
Mancato download del video di Microsoft Teams.

### ISSUE THREAD

**Issue by giordy-sudo** [sup3rgiu/MStreamDownloader#1]
Ecco alcuni risultati dell'esecuzione del processo che non viene portata a termine. Come posso risolvere? Ho seguito tutta la guida ma arrivato qui mi crea problemi. La piattaforma microsoft teams è quella relativa alla federico II. 
![WhatsApp Image 2020-05-26 at 16 53 11](https://user-images.githubusercontent.com/66011580/83011247-d8ca8900-a019-11ea-9dfc-e6ff891c8bbc.jpeg)
![WhatsApp Image 2020-05-26 at 16 54 47](https://user-images.githubusercontent.com/66011580/83011252-d9fbb600-a019-11ea-8968-6d5bac6385a9.jpeg)

**Comment by sup3rgiu** [comment]
Ciao, com'è il login della Federico II? Avviene tutto tramite Microsoft Stream oppure si viene reindirizzati ad una pagina dell'università?

**Comment by giordy-sudo** [comment]
Salve , si vengo reindirizzato . Sono queste le 3 fasi che si hanno durante
l'accesso.
[image: 1.jpg]
[image: 2.jpg]
[image: 3.jpg]

Il giorno mer 27 mag 2020 alle ore 13:28 SUPERGIU <notifications@github.com>
ha scritto:

**Comment by sup3rgiu** [comment]
Credo che le immagini non siano state caricate correttamente.

Ad ogni modo, se il login non avviene tutto tramite Microsoft Stream, il tool non può funzionare così com'è.

Se vuoi fare una prova, puoi provare ad aprire il file downloader.js e apportare queste modifiche (vedi immagine per i riferimenti delle linee):
- Linea 109: mettere `false` anziché `true`
- Linea 120: rimuoverla o commentarla con un `//` 

![Screenshot_2020-05-27-13-40-22-933_com android chrome](https://user-images.githubusercontent.com/7725068/83015047-1af6c900-a020-11ea-822e-7bbaca976d8c.jpg)

In questo modo, dovrebbe aprirsi a schermo la pagina del browser e potrai fare il login manualmente.

**Comment by giordy-sudo** [comment]
La ringrazio. Ora provo e le faccio sapere. Ecco le foto delle fasi, gliele
ricarico.

Il giorno mer 27 mag 2020 alle ore 13:44 SUPERGIU <notifications@github.com>
ha scritto:

**Comment by giordy-sudo** [comment]
Ho risolto il problema! Grazie mille, siete fortissimi .
Buona giornata.

Il giorno mer 27 mag 2020 alle ore 14:11 Stefano Maria Giordano <
stefano.giordano12@gmail.com> ha scritto:
